version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: loomos
      POSTGRES_USER: loomos
      POSTGRES_PASSWORD: loomos
    ports:
      - "5432:5432"
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: loomos
      MINIO_ROOT_PASSWORD: loomos123
    ports:
      - "9000:9000"
      - "9001:9001"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  nats:
    image: nats:2.9
    ports:
      - "4222:4222"
  loomctl:
    build: .
    command: uvicorn nexus.loomctl.app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - nats
  loomnode:
    build: .
    command: python nexus/loomnode/main.py
    depends_on:
      - loomctl
      - minio
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"